name: objectdb_google_drive_sync
description: ObjectDB database sync in Google Drive.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
   googleapis: ^2.0.0
   objectdb: ^1.2.1


dev_dependencies:
  googleapis_auth: ^1.1.0
  pedantic: ^1.9.0
  test: ^1.17.5

